### ISSUE TITLE
Module issue. 

### ISSUE THREAD

**Issue by dinspit** [ignshifts/Mass-Unban#2]
I'm install all packages, but 'module not found'

![image](https://github.com/ignshifts/Mass-Unban/assets/91454173/28a92f8c-4fe1-4872-8e2d-23083f6d5da3)

![image](https://github.com/ignshifts/Mass-Unban/assets/91454173/ea35086b-efa4-41b0-9bd8-f7eb8bf18860)

![image](https://github.com/ignshifts/Mass-Unban/assets/91454173/5b6b1db1-cb52-4e4c-8fa8-84c7dc1be041)

**Comment by ignshifts** [comment]
It's not installed because there would be a `node_modules` folder, `npm install discord.js@13`

**Comment by dinspit** [comment]
> npm install discord.js@13

![image](https://github.com/ignshifts/Mass-Unban/assets/91454173/286a50a4-506b-4d5b-a16b-ea1ba59fce29)

**Comment by ignshifts** [comment]
Try node /src/index.js or just type node and index then press tab, I dont remember the path for it

**Comment by dinspit** [comment]
> Try node /src/index.js or just type node and index then press tab, I dont remember the path for it

Nope. I even changed the directory thinking it was OneDrive
![image](https://github.com/ignshifts/Mass-Unban/assets/91454173/0ac47307-67e5-4a39-bd1d-95ef45915a18)

**Comment by ignshifts** [comment]
Do the second thing

**Comment by ignshifts** [comment]
If that does not work try npm start

**Comment by dinspit** [comment]
![image](https://github.com/ignshifts/Mass-Unban/assets/91454173/652ab488-ac1b-428e-b74c-95850807d0b4)

**Comment by ignshifts** [comment]
Install it dotenv, `npm install dotenv`

**Comment by dinspit** [comment]
> npm install dotenv

YES! It's work. thx
